- name: Deploy Zabbix5 - MYSQL
  hosts: 10.0.1.11
  roles: zabbix_db_mysql
- name: Deploy Zabbix5 - Server
  hosts: 10.0.1.12
  roles: zabbix_server
- name: Deploy Zabbix5 - Front
  hosts: 10.0.1.13
  roles: zabbix_front