- name: Configurações iniciais
  include_tasks: inicial.yml

- name: Repositorio Zabbix - CentOS8
  dnf:
    name: 'http://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm'
    state: present

- name: Instala pacotes Zabbix
  dnf:
    name:
      - zabbix-agent
      - zabbix-get
      - zabbix-sender

- name: Aplica arquivo de configuracao Zabbix Agent - CentOS8
  template:
    src: templates/zabbix_agentd_centos.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
    group: zabbix
    mode: 0644

- name: Altera permissão Zabbix
  file:
    path: /etc/zabbix/
    mode: 0775
    owner: zabbix
    group: zabbix  

- name: Habilita e inicia servico
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes
