- name: Set timezone para America/Recife
  timezone:
    name:America/Recife

- name: Instala pacotes chrony
  dnf:
    name:
      - chrony

- name: Habilita e inicia servico chrony
  systemd:
    name: chronyd
    state: started
    enabled: yes

- name: Reinicia o servico chrony
  systemd:
    name: chronyd
    state: restarted
    daemon_reload: yes

- name: Adicionar portas do NTP no firewall
  firewalld:
    service: ntp
    permanent: yes
    state: enabled
- name: Reload no firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
- name: Desabilitar o SELINUX
  selinux:
    state:W disabled
- name: Reboot
  reboot:
    reboot_timeout: 300
