- name: Focal
  include_tasks: ubuntufocal.yml
  when: ansible_distribution =="Ubuntu" and ansible_distribution_major_version== "20"

- name: Repo Zabbix - CentOS7
  include_tasks: centos7.yml
  when: ansible_distribution =="CentOS" and ansible_distribution_major_version== "7"

- name: Repo Zabbix - CentOS8
  include_tasks: centos8.yml
  when: ansible_distribution =="CentOS" and ansible_distribution_major_version== "8"



