- name: Mudar Hostname
  hostname:
    name: "{{ zabbix_server_hostname }}"

- name: Repositorio Zabbix - CentOS8
  dnf:
    name: 'http://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm'
    state: present

- name: Instala pacotes Zabbix
  dnf:
    name:
      - zabbix-server
      - mysql

- name: Import initial schema zabbix database
  shell: "zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -h {{ zabbix_db }} -u{{ zabbix_db_server_user }} -p{{ zabbix_db_server_pass }} zabbix"

- name: Copiar arquivo de configuração do server
  template:
    src: templates/zabbix_server.j2
    dest: /etc/zabbix/zabbix_server.conf

- name: Habilita e inicia servico zabbix-server
  systemd:
    name: zabbix-server
    state: started
    enabled: yes

- name: Adicionar portas do Zabbix Server no firewall
  firewalld:
    port: 10050/tcp
    permanent: yes
    state: enabled

- name: Adicionar portas do Zabbix Server no firewall
  firewalld:
    port: 10051/tcp
    permanent: yes
    state: enabled

- name: Reload no firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes