- name: Set timezone para {{ timezone }}
  timezone:
    name: "{{ timezone }}"

- name: Instala pacotes de utilitários
  dnf:
    name:
      - net-tools
      - vim
      - nano
      - epel-release
      - wget
      - curl
      - tcpdump
      - python3
    state: latest

- name: Instala pacotes chrony
  dnf:
    name:
      - chrony

- name: Habilita e inicia servico chrony
  systemd:
    name: chronyd
    state: started
    enabled: yes

- name: Reinicia o servico chrony
  systemd:
    name: chronyd
    state: restarted
    daemon_reload: yes

- name: Adicionar portas do NTP no firewall
  firewalld:
    service: ntp
    permanent: yes
    state: enabled
- name: Reload no firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
- name: Desabilitar o SELINUX
  selinux:
    state: disabled
- name: Reboot
  reboot:
    reboot_timeout: 300
